/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 */
/* 76576500 */

#include <stdio.h>

#define TRUE 1
#define FALSE 0

long int triangle(long int n, long int prev)
{
    return n + prev;
}

long int divisors(long int n)
{
    long int divisors = 1;
    for (long int i = 0; i <= n / 2; i++)
    {
        if (n % i == 0)
        {
            divisors++;
        }
    }

    return divisors;
}

long int naive()
{
    long int n = 0;
    long int triangleValue = 0;
    while (TRUE)
    {
        triangleValue = triangle(n, triangleValue);
        long int div = divisors(triangleValue);
        if (n % 100 == 0) {
            printf("%ld, %ld\n", triangleValue, div);
        }
        if (div > 500)
        {
            printf("%ld, %ld\n", triangleValue, div);
            return triangleValue;
        }
        n++;
    }

    return 0;
}


int main(void)
{
    printf("%ld\n", naive());
    return 0;
}
